# use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'http://39.96.8.150:10080/l405023944/LenzSDK_iOS.git'

target 'LenzCameraNativeModuleForRN_Example' do
  # 使用私有库，由于发布
#  pod 'LenzSDK' ,'~> 1.0.3'
# 使用本地路径，用于开发
  pod 'LenzSDK', :path => '../'

end
